(function () {
  'use strict';

  // Schedule data lives in window.SmokerSim.Menu (menuLibrary.js).
  // This module turns a (templateId, serveTime) pair into a fully-
  // expanded event list, an RFC 5545 .ics file, or a flat text plan.

  function pad(n) { return String(n).padStart(2, '0'); }

  function fmtFloating(d) {
    return d.getFullYear() + pad(d.getMonth() + 1) + pad(d.getDate())
      + 'T' + pad(d.getHours()) + pad(d.getMinutes()) + pad(d.getSeconds());
  }

  function fmtUTCStamp(d) {
    return d.getUTCFullYear() + pad(d.getUTCMonth() + 1) + pad(d.getUTCDate())
      + 'T' + pad(d.getUTCHours()) + pad(d.getUTCMinutes()) + pad(d.getUTCSeconds()) + 'Z';
  }

  function fmtClock(d) { return pad(d.getHours()) + ':' + pad(d.getMinutes()); }

  function fmtDay(d) {
    return d.toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' });
  }

  // Resolve `source` into { schedule, name, name_zh, icon, id }.
  // Source can be:
  //   - a string templateId (looked up in window.SmokerSim.Menu)
  //   - an object { schedule, name, name_zh, icon, id } directly
  function resolveSource(source) {
    if (typeof source === 'string') {
      var Menu = window.SmokerSim && window.SmokerSim.Menu;
      if (!Menu) throw new Error('menuLibrary.js must load before icsGenerator.js');
      var tpl = Menu.get(source);
      if (!tpl) throw new Error('Unknown template: ' + source);
      return tpl;
    }
    if (source && Array.isArray(source.schedule)) return source;
    throw new Error('icsGenerator: source must be a templateId or {schedule}');
  }

  function buildEvents(serveAt, source) {
    var tpl = resolveSource(source);
    return tpl.schedule.map(function (step, i) {
      var start = new Date(serveAt.getTime() + step.offsetMin * 60000);
      var end = new Date(start.getTime() + step.dur * 60000);
      return {
        index: i,
        offsetMin: step.offsetMin,
        title: step.title,
        title_zh: step.title_zh,
        body: step.body,
        body_zh: step.body_zh,
        start: start,
        end: end,
        clock: fmtClock(start),
        day: fmtDay(start),
        durMin: step.dur
      };
    });
  }

  // RFC 5545 escaping
  function esc(s) {
    return String(s)
      .replace(/\\/g, '\\\\')
      .replace(/;/g, '\\;')
      .replace(/,/g, '\\,')
      .replace(/\r?\n/g, '\\n');
  }

  // RFC 5545 line folding: max 75 octets, continuation begins with single space
  function fold(line) {
    if (line.length <= 75) return line;
    var out = [];
    var i = 0;
    while (i < line.length) {
      out.push(i === 0 ? line.slice(0, 75) : ' ' + line.slice(i, i + 74));
      i += (i === 0 ? 75 : 74);
    }
    return out.join('\r\n');
  }

  function buildICS(serveAt, source) {
    var tpl = resolveSource(source);
    var events = buildEvents(serveAt, source);
    var stamp = fmtUTCStamp(new Date());
    var slug = fmtFloating(serveAt);
    var calName = (tpl.name || 'BBQ Cook') + (tpl.name_zh ? ' · ' + tpl.name_zh : '');
    var lines = [
      'BEGIN:VCALENDAR',
      'VERSION:2.0',
      'PRODID:-//BBQ-Master//Smoker Dynamics//EN',
      'CALSCALE:GREGORIAN',
      'METHOD:PUBLISH',
      fold('X-WR-CALNAME:' + esc(calName))
    ];
    events.forEach(function (e, i) {
      var summary = e.title + ' · ' + e.title_zh;
      var description = e.body + '\n\n' + e.body_zh;
      lines.push('BEGIN:VEVENT');
      lines.push(fold('UID:' + (tpl.id || 'custom') + '-' + slug + '-' + i + '@smoker-dynamics'));
      lines.push('DTSTAMP:' + stamp);
      lines.push('DTSTART:' + fmtFloating(e.start));
      lines.push('DTEND:' + fmtFloating(e.end));
      lines.push(fold('SUMMARY:' + esc(summary)));
      lines.push(fold('DESCRIPTION:' + esc(description)));
      lines.push('BEGIN:VALARM');
      lines.push('TRIGGER:-PT5M');
      lines.push('ACTION:DISPLAY');
      lines.push(fold('DESCRIPTION:' + esc('In 5 min · 5 分钟后：' + e.title)));
      lines.push('END:VALARM');
      lines.push('END:VEVENT');
    });
    lines.push('END:VCALENDAR');
    return lines.join('\r\n') + '\r\n';
  }

  function buildText(serveAt, source) {
    var tpl = resolveSource(source);
    var events = buildEvents(serveAt, source);
    var lines = [
      (tpl.icon || '🔥') + ' ' + (tpl.name || 'BBQ Cook')
        + (tpl.name_zh ? ' · ' + tpl.name_zh : ''),
      'Serving ' + fmtClock(serveAt) + ' · ' + fmtDay(serveAt),
      ''
    ];
    var lastDay = null;
    events.forEach(function (e) {
      if (e.day !== lastDay) {
        if (lastDay !== null) lines.push('');
        lines.push('— ' + e.day + ' —');
        lastDay = e.day;
      }
      lines.push(e.clock + '  ' + e.title + ' · ' + e.title_zh);
    });
    lines.push('');
    lines.push('Generated by Smoker Dynamics · 由烟熏动力学生成');
    return lines.join('\n');
  }

  window.SmokerSim = window.SmokerSim || {};
  window.SmokerSim.ICS = {
    buildEvents: buildEvents,
    buildICS: buildICS,
    buildText: buildText
  };
})();
